CREATE DATABASE POC_AzureDevOps
GO

USE POC_AzureDevOps
GO

CREATE TABLE AzureServiceConfiguration
(
	[ID] INT NOT NULL IDENTITY PRIMARY KEY,
	[URL] VARCHAR(200) NOT NULL,
	[Organization] VARCHAR(50) NOT NULL,
	[AccessToken] VARCHAR(200) NOT NULL,
	[Project] VARCHAR(30) NOT NULL,
	[LastWorkItemID] INT NULL
)

CREATE TABLE WorkItem
(
	[ID] INT NOT NULL PRIMARY KEY,
	[Type] VARCHAR(20) NOT NULL,
	[Title] VARCHAR(200) NOT NULL,
	[CreatedOn] DATETIME NOT NULL
)